language: ruby
rvm:
 - 2.7.0
 - jruby
services:
 - postgresql
script:
 - gem install bundler:1.17.3
 - bundle install
 - bundle exec rails db:create
 - bundle exec rails db:migrate
 - bundle exec rspec
